function freezeRule(rule) {
  const frozenRule = { ...rule };
  if (Array.isArray(frozenRule.includesAll)) frozenRule.includesAll = Object.freeze([...frozenRule.includesAll]);
  if (Array.isArray(frozenRule.includesAny)) frozenRule.includesAny = Object.freeze([...frozenRule.includesAny]);
  if (frozenRule.extras && typeof frozenRule.extras === "object") {
    frozenRule.extras = Object.freeze(
      Object.fromEntries(
        Object.entries(frozenRule.extras).map(([key, value]) => [
          key,
          Array.isArray(value) ? Object.freeze([...value]) : value,
        ])
      )
    );
  }
  return Object.freeze(frozenRule);
}

function freezeRuleList(rules) {
  return Object.freeze(rules.map(freezeRule));
}

function freezeEntries(entries) {
  return Object.freeze(entries.map((entry) => Object.freeze([...entry])));
}

function isChocolateFamily(raw) {
  return [
    "chocolate chip",
    "chopped chocolate",
    "dark chocolate",
    "white chocolate",
    "semi-sweet chocolate",
    "semisweet chocolate",
  ].some((term) => raw.includes(term));
}

export const canonicalNoteTokens = Object.freeze([
  "divided",
  "for dredging",
  "for dusting",
  "plus more",
  "packed",
  "lightly packed",
  "sifted",
]);

// These rule lists are intentionally ordered. Keep specific ingredient labels
// before broader labels that would also match the same text.
export const leadingIngredientRules = freezeRuleList([
  {
    includesAny: ["dark or semi sweet chocolate", "dark or semi-sweet chocolate"],
    base: "chocolate",
    display: "Chocolate (dark OR semi-sweet)",
    extras: { notes: [] },
  },
  {
    includesAll: ["butter lettuce", "red leaf lettuce"],
    base: "butter lettuce or red leaf lettuce",
  },
  {
    includesAll: ["lard", "unsalted butter"],
    base: "lard or unsalted butter",
  },
]);

export const commodityIngredientRules = freezeRuleList([
  { match: (raw) => raw.includes("all-purpose flour") || raw === "flour", base: "all-purpose flour" },
  { includes: "granulated sugar", base: "granulated sugar" },
  { includesAny: ["powdered sugar", "confectioners"], base: "powdered sugar" },
  { includes: "light brown sugar", base: "light brown sugar" },
  { includes: "dark brown sugar", base: "dark brown sugar" },
  { includes: "lemon zest", base: "lemon zest" },
  { includes: "lemon juice", base: "lemon juice" },
  { includes: "lemon", base: "lemon" },
  { includesAll: ["greek yogurt", "sour cream"], base: "greek yogurt or sour cream" },
  { includes: "greek yogurt", base: "greek yogurt" },
  { includes: "sweetened condensed milk", base: "sweetened condensed milk" },
  { includes: "evaporated milk", base: "evaporated milk" },
  { includes: "buttermilk", base: "buttermilk" },
  { includes: "coconut milk", base: "coconut milk" },
  { includes: "peanut butter", base: "peanut butter" },
  { includes: "almond butter", base: "almond butter" },
  { includes: "milk chocolate", base: "milk chocolate" },
  { includes: "unsalted butter", base: "unsalted butter" },
  { includes: "salted butter", base: "salted butter" },
  { includes: "butter", base: "butter" },
  { includes: "cream cheese", base: "cream cheese" },
  { includes: "whole milk", base: "whole milk" },
  { includes: "skim milk", base: "skim milk" },
  { includes: "2% milk", base: "2% milk" },
  { includes: "milk", base: "milk" },
  { pattern: /\begg\s+yolks?\b/, base: "egg yolk" },
  { pattern: /\begg\s+whites?\b/, base: "egg whites" },
  { pattern: /\beggs?\b/, base: "egg" },
  { includes: "sour cream", base: "sour cream" },
  { includes: "parmigiano reggiano", base: "parmigiano reggiano cheese" },
  { includesAny: ["parmesan", "parmigiano"], base: "parmesan cheese" },
  { includes: "heavy whipping cream", base: "heavy whipping cream" },
  { includes: "heavy cream", base: "heavy cream" },
  { includes: "cheddar", base: "cheddar cheese" },
  { includes: "flaky sea salt", base: "flaky sea salt" },
  { includes: "flaked sea salt", base: "flaked sea salt" },
  { includes: "flaky salt", base: "flaky salt" },
  { includes: "celery salt", base: "celery salt" },
  { includes: "sea salt", base: "sea salt" },
  { includes: "kosher salt", base: "kosher salt" },
  { includes: "salt", base: "salt" },
  { includes: "black pepper", base: "black pepper" },
  { pattern: /^(?:ground\s+)?pepper$/, base: "pepper" },
]);

export const ingredientRules = freezeRuleList([
  { includesAll: ["granulated garlic", "garlic powder"], base: "granulated garlic or garlic powder" },
  { includes: "garlic powder", base: "garlic powder" },
  { includes: "onion powder", base: "onion powder" },
  { includes: "garlic", base: "garlic" },
  { includes: "yellow onion", base: "yellow onion" },
  { includes: "white onion", base: "white onion" },
  { includes: "roasted red peppers", base: "roasted red peppers" },
  { includes: "green bell pepper", base: "green bell pepper" },
  { includes: "red bell pepper", base: "red bell pepper" },
  { includes: "bell pepper", base: "bell pepper" },
  {
    includesAny: ["cabbage and carrot coleslaw mix", "coleslaw mix"],
    base: "plain shredded cabbage and carrot coleslaw mix",
  },
  { includes: "carrot", base: "carrot" },
  { includes: "celery seed", base: "celery seed" },
  { includes: "celery", base: "celery" },
  { includesAll: ["potato bun", "brioche bun"], base: "potato bun or brioche bun" },
  { includes: "potato bun", base: "potato bun" },
  { includes: "brioche bun", base: "brioche bun" },
  { includes: "mashed potatoes", base: "mashed potatoes" },
  { includes: "sweet potato", base: "sweet potato" },
  { includes: "yukon gold", base: "yukon gold potato", display: "Yukon gold potato" },
  { includes: "baby yellow", base: "baby yellow potato" },
  { includes: "potato", base: "potato" },
  {
    includesAll: ["chicken breast", "boneless skinless"],
    base: "boneless skinless chicken breast",
  },
  { includes: "chicken breast", base: "chicken breast" },
  { includes: "flank steak", base: "flank steak" },
  {
    includesAll: ["top sirloin steak", "strip steak", "flat iron steak"],
    base: "top sirloin steak, strip steak, or flat iron steak",
  },
  {
    includesAll: ["ribeye", "top sirloin", "skirt steak"],
    base: "boneless ribeye, top sirloin, or skirt steak",
  },
  { includes: "thick-cut ribeye steak", base: "thick-cut ribeye steak" },
  { includes: "ribeye", base: "ribeye steak" },
  { includes: "top sirloin", base: "top sirloin steak" },
  { includes: "new york strip", base: "new york strip steak", display: "New York strip steak" },
  { includes: "strip steak", base: "strip steak" },
  { includes: "flat iron steak", base: "flat iron steak" },
  { includes: "skirt steak", base: "skirt steak" },
  { includes: "80/20 ground beef", base: "80/20 ground beef" },
  { includes: "85/15 ground beef", base: "85/15 ground beef" },
  { includes: "lean ground beef", base: "lean ground beef" },
  { includes: "grass-fed ground beef", base: "grass-fed ground beef" },
  { includes: "ground beef", base: "ground beef" },
  { includes: "short rib", base: "beef short rib" },
  { includes: "beef tenderloin", base: "beef tenderloin" },
  { includes: "prime rib", base: "prime rib roast" },
  { includes: "crushed tomatoes", base: "crushed tomatoes" },
  { includes: "fire-roasted diced tomatoes", base: "fire-roasted diced tomatoes" },
  { includes: "diced tomatoes", base: "diced tomatoes" },
  { includes: "tomato sauce", base: "tomato sauce" },
  { includes: "tomato paste", base: "tomato paste" },
  { includes: "kidney beans", base: "kidney beans" },
  { includes: "pinto beans", base: "pinto beans" },
  { includes: "cream of chicken soup", base: "cream of chicken soup" },
  { includes: "puff pastry", base: "puff pastry dough" },
  { includesAll: ["vanilla bean paste", "extract"], base: "vanilla extract or paste" },
  { includes: "vanilla bean paste", base: "vanilla bean paste" },
  { includesAny: ["vanilla extract", "vanilla paste"], base: "vanilla extract or paste" },
  { includes: "egg yolk", base: "egg yolk" },
  { includes: "american cheese slice", base: "american cheese slice", display: "American cheese slice" },
  { includes: "american cheese", base: "american cheese", display: "American cheese" },
  { includes: "brown sugar", base: "brown sugar" },
  { includes: "maple syrup", base: "maple syrup" },
  { includes: "blueberries", base: "blueberries" },
  { includes: "raspberries", base: "raspberries" },
  { includes: "mixed berries", base: "mixed berries" },
  { includes: "berries", base: "berries" },
  { includes: "banana", base: "banana" },
  { includes: "walnut", base: "walnuts" },
  { includes: "pecan", base: "pecans" },
  { includes: "pistachio", base: "pistachios" },
  { includes: "nuts of choice", base: "nuts of choice" },
  { includesAny: ["pasta of choice", "pasta"], base: "pasta" },
  { includes: "low-sodium beef broth", base: "low-sodium beef broth" },
  { includes: "beef broth", base: "beef broth" },
  { includes: "low-sodium chicken broth", base: "low-sodium chicken broth" },
  { includes: "chicken broth", base: "chicken broth" },
  { includes: "cinnamon", base: "cinnamon" },
  { includes: "red pepper flakes", base: "red pepper flakes" },
  { includes: "peanut or vegetable oil", base: "peanut or vegetable oil" },
  { includes: "olive or avocado oil", base: "olive or avocado oil" },
  { includes: "pizza oil", base: "pizza oil or olive oil" },
  { includes: "oil of choice", base: "oil of choice" },
  { includes: "mayonnaise", base: "mayonnaise" },
  { includes: "yellow mustard seed", base: "yellow mustard seed" },
  { includes: "yellow mustard", base: "yellow mustard" },
  {
    includes: "louisiana-style cayenne hot sauce",
    base: "louisiana-style cayenne hot sauce",
    display: "Louisiana-style cayenne hot sauce",
  },
  {
    includes: "louisiana-style hot sauce",
    base: "louisiana-style hot sauce",
    display: "Louisiana-style hot sauce",
  },
  { includes: "hot sauce", base: "hot sauce" },
  { includes: "pizza sauce", base: "pizza sauce" },
  { includes: "cheese of choice", base: "cheese", display: "cheese" },
  { includes: "iceberg lettuce", base: "iceberg lettuce" },
  { includes: "red leaf lettuce", base: "red leaf lettuce" },
  { includes: "butter lettuce", base: "butter lettuce" },
  { includes: "lettuce", base: "lettuce" },
  { includes: "white chocolate", base: "white chocolate" },
  { includes: "dark chocolate", base: "dark chocolate" },
  { includes: "semisweet chocolate chips", base: "semisweet chocolate chips" },
  { includes: "semi-sweet chocolate chips", base: "semi-sweet chocolate chips" },
  { includes: "semi-sweet", base: "semi-sweet chocolate" },
  { includes: "semisweet", base: "semisweet chocolate" },
  { match: isChocolateFamily, base: "chocolate" },
  { includesAll: ["avocado oil", "coconut oil"], base: "avocado oil or coconut oil" },
  { includes: "avocado oil", base: "avocado oil" },
  { includesAll: ["olive oil", "extra-virgin"], base: "extra-virgin olive oil" },
  { includes: "olive oil", base: "olive oil" },
  { includes: "chipotle peppers in adobo", base: "chipotle peppers in adobo sauce" },
  { includes: "sun-dried tomatoes", base: "sun-dried tomatoes" },
  { includes: "broccoli", base: "broccoli" },
  { includes: "green onion", base: "green onion" },
  { includes: "onion", base: "onion" },
  { includes: "fresh ginger", base: "fresh ginger" },
  { includes: "ginger", base: "ginger" },
  { includes: "peach", base: "peach" },
  { includes: "graham cracker", base: "graham crackers" },
  { includes: "croissant", base: "croissants" },
  { includes: "refrigerated crescent rolls", base: "refrigerated crescent rolls" },
  { includes: "pineapple slices", base: "pineapple slices" },
  { includes: "maraschino cherries", base: "maraschino cherries" },
  { includes: "vanilla bean", base: "vanilla bean" },
  { includes: "basil pesto", base: "basil pesto" },
  { includes: "basil", base: "basil" },
  { includes: "sourdough discard", base: "sourdough discard" },
  { includes: "freeze-dried strawberries", base: "freeze-dried strawberries" },
  {
    includesAny: ["dill pickle chips", "hamburger dill pickle chips", "crinkle-cut dill pickles"],
    base: "dill pickle chips",
  },
  { includesAny: ["pickle chips", "pickles"], base: "pickles" },
  { includes: "bacon", base: "bacon" },
  { includes: "salami", base: "deli salami" },
  { includes: "pepperoni", base: "deli pepperoni" },
  { includes: "ice cream", base: "ice cream" },
  { includesAny: ["dried bay leaf", "dried bay leaves"], base: "dried bay leaf" },
  { includesAny: ["bay leaf", "bay leaves"], base: "bay leaf" },
  { includes: "italian parsley", base: "italian parsley" },
  { includes: "fresh parsley", base: "fresh parsley" },
  { includes: "parsley", base: "parsley" },
  { includes: "fresh rosemary", base: "fresh rosemary" },
  { match: (raw) => raw.includes("rosemary") && raw.includes("sprig"), base: "rosemary sprig" },
  { includes: "rosemary", base: "rosemary" },
  { includes: "fresh thyme", base: "fresh thyme" },
  { match: (raw) => raw.includes("thyme") && raw.includes("sprig"), base: "thyme sprig" },
  { includes: "thyme", base: "thyme" },
]);

export const unitAliasEntries = freezeEntries([
  ["tsp", "tsp"],
  ["teaspoon", "tsp"],
  ["teaspoons", "tsp"],
  ["tbsp", "tbsp"],
  ["tablespoon", "tbsp"],
  ["tablespoons", "tbsp"],
  ["cup", "cup"],
  ["cups", "cup"],
  ["oz", "oz"],
  ["ounce", "oz"],
  ["ounces", "oz"],
  ["lb", "lb"],
  ["lbs", "lb"],
  ["pound", "lb"],
  ["pounds", "lb"],
  ["g", "g"],
  ["gram", "g"],
  ["grams", "g"],
  ["kg", "kg"],
  ["kilogram", "kg"],
  ["kilograms", "kg"],
  ["ml", "ml"],
  ["milliliter", "ml"],
  ["milliliters", "ml"],
  ["l", "l"],
  ["liter", "l"],
  ["liters", "l"],
  ["bag", "bag"],
  ["bags", "bag"],
  ["block", "block"],
  ["blocks", "block"],
  ["bottle", "bottle"],
  ["bottles", "bottle"],
  ["bunch", "bunch"],
  ["bunches", "bunch"],
  ["can", "can"],
  ["cans", "can"],
  ["clove", "clove"],
  ["cloves", "clove"],
  ["egg", "egg"],
  ["eggs", "egg"],
  ["egg white", "egg white"],
  ["egg whites", "egg white"],
  ["jar", "jar"],
  ["jars", "jar"],
  ["leaf", "leaf"],
  ["leaves", "leaf"],
  ["package", "package"],
  ["packages", "package"],
  ["pkg", "package"],
  ["pkgs", "package"],
  ["sheet", "sheet"],
  ["sheets", "sheet"],
  ["slice", "slice"],
  ["slices", "slice"],
  ["sprig", "sprig"],
  ["sprigs", "sprig"],
  ["stalk", "stalk"],
  ["stalks", "stalk"],
  ["stick", "stick"],
  ["sticks", "stick"],
  ["yolk", "yolk"],
  ["yolks", "yolk"],
]);
